name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        LIBLUA:
          # TODO
          #- "libluajit-5.1-dev"
          #- "liblua5.3-dev"
          - "liblua5.2-dev"
          #- "liblua5.1-0-dev"
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - name: Setup packages
        run: sudo apt install -y lua5.2 clang ${{ matrix.LIBLUA }}

      - run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S . -B build

      - run: cmake --build build --parallel $(nproc)

      - run: cmake --build build --target test

  build-rock:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - run: sudo apt install -y lua5.2 liblua5.2-dev clang

      - run: luarocks --local build

      - run: luarocks --local make
