name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        LIBLUA:
          # TODO
          #- "libluajit-5.1-dev"
          #- "liblua5.3-dev"
          - "liblua5.2-dev"
          #- "liblua5.1-0-dev"
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - name: Setup packages
        run: sudo apt install -y lua5.2 clang-13 libclang-common-13-dev ${{ matrix.LIBLUA }}

      - run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DENABLE_TESTING=ON -S . -B build

      - run: cmake --build build --parallel $(nproc)

      - run: cmake --build build --target test
