name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        LUA: ["5.1.5", "5.2.4", "5.3.5", "5.4.1", "luajit-2.0.5", "luajit-2.1.0-beta3"]
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - name: Setup LuaJIT (${{ matrix.LUA }})
        if: matrix.LUA != 'tarantool'
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.LUA }}

      - name: Run CMake generation
        run: cmake -S . -B build

      - name: Building
        run: cmake --build build --parallel $(nproc)

      - name: Testing
        run: cmake --build build --target test
